# Install and configure MailHog.
- name: MAILHOG | Ensure mailhog install directory exists.
  file:
    path: "{{ mailhog_install_dir }}"
    owner: root
    group: root
    state: directory
    mode: 0755

- name: MAILHOG | Download MailHog binary.
  get_url:
    url: "{{ mailhog_binary_url }}"
    dest: "{{ mailhog_install_dir }}/mailhog"
    owner: root
    group: root
    mode: 0755

- name: MAILHOG | Install the daemonize package.
  yum: pkg=daemonize state=installed

- name: Copy mailhog systemd unit file into place
  template:
    src: mailhog.unit.j2
    dest: /etc/systemd/system/mailhog.service
    owner: root
    group: root
    mode: 0755

- name: MAILHOG | Ensure mailhog is enabled and will start on boot.
  service: name=mailhog state=started enabled=yes

- name: MAILHOG | Install sSMTP.
  yum: pkg=ssmtp state=installed

- name: MAILHOG | Copy sSMTP configuration.
  template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
    owner: root
    group: root
    mode: 0644

- name: MAILHOG | Specify HTTP authentication password file
  shell: echo "{{ mailhog_http_authuser }}:`{{ mailhog_install_dir }}/mailhog bcrypt {{ mailhog_http_authpass | default(mailhog_http_authuser) }}`" > /etc/ssmtp/http_auth
  when: mailhog_http_authuser is defined

# PHP configuration files
- ini_file: dest="{{ php_ini_file }}"
    section="{{ item.0.section }}"
    option="{{ item.1.key }}"
    value="{{ item.1.val }}"
  with_subelements:
    - "{{ mailhog_php_ini }}"
    - options
  notify:
    - restart php-fpm


