---
partition_var_lib_mysql: True

mariadb_root_password: root

innodb_buffer_pool_size: 1024

max_connections: 500

max_allowed_packet: 256M

innodb_buffer_pool_instances: 6

innodb_concurrency: 16

connection_timeout: 5
