---

# Copy backup.sh to it's place
- template:
    src=backup.sh.j2
    dest=/root/backup.sh
    owner=root
    group=nobody
    mode=0750

# Setup backup cron job
- cron: name="Backup cron job" minute="{{ backup_cron.minute }}" hour="{{ backup_cron.hour }}" job="/root/backup.sh > /dev/null 2>&1" state="present"
