language: python
python: '2.7'
sudo: required
env:
- CONTAINER_ID=$(mktemp)
branches:
  only:
  - centos7
services:
- docker
before_install:
- sudo docker pull centos:7
- sudo docker build --rm=true --file=Dockerfile --tag=centos:ansible .
script:
- sudo docker run --detach --privileged --volume="${PWD}":/WunderMachina:rw --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro
  centos:ansible /usr/lib/systemd/systemd > "${CONTAINER_ID}"
- sudo docker exec "$(cat ${CONTAINER_ID})" ansible-playbook -i /WunderMachina/tests/test-inventory
  /WunderMachina/tests/test.yml --syntax-check || (echo 'Ansible playbook syntax check
  failed' && exit 2 )
- sudo docker exec "$(cat ${CONTAINER_ID})" ansible-playbook -i /WunderMachina/tests/test-inventory
  /WunderMachina/tests/test.yml -vvv --connection=local --sudo || ( echo 'First run
  failed' && exit 2 )
- sudo docker stop "$(cat ${CONTAINER_ID})"
notifications:
  email: false
  hipchat:
    rooms:
      secure: JM+TMxOSehVBgdT/f/IEDI52hqo1M9EM2vYIb4i8pMt3vQ5K6piMeOQ3DE0xjkNSn56LtwzY4CPTEq1/2omp5N6sQTZUWj82abgGaGNupGr9kuSSJGVrCi6YwKl3oXiWRBZ9DQcLvAwM3374G0LrrUX+8Zf4xCM8O8UzB44NCVhhrjlfz9HtA86COE3VKw9OK29aPWjoAazM1hRoiTVRIqH7Pz+KeDIIssJn40xMipiL8cpX3i3EGxY/JJAHOwoP+XLp+YGvs7+iALXKNTEMgFyO/G9g5HNsI2UoKqm1A0DvLWsVFX+1HSHlSLiCY53xdWf2l2K5YjfgLrhYEGXDBvgXOv9qFrjpTfZndoj3lJsIg1Kp3HtjGI3Cqrm6III5wNNkmp2dpvUEUvwea0Cjj8vdBFy7kECZNu3KzT0naQq9FrKliMBgqYyzZgyAXSeXsTiXFUahTaOGF7RIpzqAbVyA5FJq96wLdzB4OfuRsd/OCSHWq4l/Apx1y/a/QsYst+HqRpr5qZZ4mB8P+h8FDzwj5+dxncSHlbpmTmweoru4ysC1WDLYzbL9LVmeKzXwzK0a5sSb2VuxWtbJ9i9Nf/JXQ7GP3pXIPN9xXaLDhjKiFWydLcjGbypKu9A/PFvYzuyOCvxX5SXfj8g7kkb2BEepBBoGadaptkHAkTI35RU=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html