language: python
python: '2.7'
sudo: required
env:
  - CONTAINER_ID=$(mktemp)

branches:
  only:
  - centos7

services:
  - docker

before_install:
  - sudo docker pull centos:7
  - sudo docker build --rm=true --file=Dockerfile --tag=centos:ansible .

script:
  # Run container in detached state
  - sudo docker run --detach --privileged --volume="${PWD}":/WunderMachina:rw --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro centos:ansible /usr/lib/systemd/systemd > "${CONTAINER_ID}"
  # Run tests in Container
  - sudo docker exec "$(cat ${CONTAINER_ID})" /bin/bash -c "/WunderMachina/tests/test-in-docker.sh"
  # Clean up
  - sudo docker stop "$(cat ${CONTAINER_ID})"

notifications:
  email: false
#  hipchat:
#    rooms: