language: python
python: '2.7'
sudo: required

branches:
  only:
  - centos7

services:
  - docker

before_install:
  - sudo docker pull centos:7
  - sudo docker build --rm=true --tag=travistest .

script:
  # Run container in detached state
  - sudo docker run --detach --privileged --volume="${PWD}":/WunderMachina:rw --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro travistest /usr/lib/systemd/systemd > /tmp/container_id
  # Run tests in Container
  - sudo docker exec "$(cat /tmp/container_id)" /bin/bash -c "/WunderMachina/tests/test-in-docker.sh"
  # Clean up
  - sudo docker stop "$(cat /tmp/container_id)"

notifications:
  email: false
#  hipchat:
#    rooms: