language: python
python: '2.7'
sudo: required
env:
  - CONTAINER_ID=$(mktemp)

branches:
  only:
  - centos7

services:
  - docker

before_install:
  - sudo docker pull centos:7
  - sudo docker build --rm=true --file=Dockerfile --tag=centos:ansible .

script:
  # Run container in detached state
  - sudo docker run --detach --privileged --volume="${PWD}":/WunderMachina:rw --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro centos:ansible /usr/lib/systemd/systemd > "${CONTAINER_ID}"
  # Create ansible.cfg
  - sudo docker exec "$(cat ${CONTAINER_ID})" mkdir /etc/ansible && printf "[defaults]\nroles_path = /WunderMachina/playbook/roles" > /etc/ansible/ansible.cfg
  # Run syntac check
  - sudo docker exec "$(cat ${CONTAINER_ID})" ansible-playbook -i /WunderMachina/tests/test-inventory /WunderMachina/tests/test.yml --syntax-check || (echo "ansible playbook syntax check was failed" && exit 2 )
  # Clean up
  - sudo docker stop "$(cat ${CONTAINER_ID})"

notifications:
  email: false
#  hipchat:
#    rooms: