language: python
python: '2.7'
sudo: required
env:
  - CONTAINER_ID=$(mktemp)

branches:
  only:
  - centos7

services:
  - docker

before_install:
  - sudo docker pull centos:7
  - sudo docker build --rm=true --file=Dockerfile --tag=centos:ansible .

script:
  # Run container in detached state
  - sudo docker run --detach --privileged --volume="${PWD}":/WunderMachina:rw --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro centos:ansible /usr/lib/systemd/systemd > "${CONTAINER_ID}"
  # Run syntac check
  - sudo docker exec "$(cat ${CONTAINER_ID})" ansible-playbook -i /WunderMachina/tests/test-inventory /WunderMachina/tests/test.yml --syntax-check || (echo 'Ansible playbook syntax check failed' && exit 2 )
  # First run
  - sudo docker exec "$(cat ${CONTAINER_ID})" ansible-playbook -i /WunderMachina/tests/test-inventory /WunderMachina/tests/test.yml -vvv --connection=local --sudo || ( echo 'First run failed' && exit 2 )
  # Check that the playbook is idempotent
  - sudo docker exec "$(cat ${CONTAINER_ID})" ansible-playbook -i /WunderMachina/tests/test-inventory /WunderMachina/tests/test.yml -vvvv --connection=local --sudo | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test passed' ) || (echo 'Idempotence test failed' && exit 1)
  # Clean up
  - sudo docker stop "$(cat ${CONTAINER_ID})"

notifications:
  email: false
#  hipchat:
#    rooms: