language: python
python: '2.7'
sudo: required

branches:
  only:
  - centos7

services:
  - docker

before_install:
  - docker pull centos:7

script:
 # Run tests in Container
 - docker run --rm=true -v `pwd`:/WunderMachina:rw centos:7 /bin/bash -c "/WunderMachina/tests/test-in-docker.sh"

notifications:
  email: false
#  hipchat:
#    rooms: