---

- name: Set varnish package with version.
  set_fact:
    varnish_package: "varnish{{ varnish_version|replace('.', '') }}"

- include: "yum.yml"

- yum:
    name={{ item }}
    state=present
  with_items:
    - varnish

- name: ensure varnish is running now and on boot
  service: name=varnish state=started enabled=yes

- name: Varnish default.vcl
  template: src=default.vcl.j2 dest=/etc/varnish/default.vcl

- name: Varnish sysconfig
  template: src=varnish.j2 dest=/etc/sysconfig/varnish
  notify:
    - restart varnish
