---
- name: Ensure Varnish dependencies are installed.
  yum: name={{ item }} state=present
  with_items:
    - yum-utils
    - pygpgme

- name: Install packagecloud varnish repository
  copy:
    src=varnish.repo
    dest=/etc/yum.repos.d/varnish.repo
  register: varnish_packagecloud_repo_addition

- name: Refresh yum metadata cache if repo changed.
  command: >
    yum clean metadata
    warn=no
  when: varnish_packagecloud_repo_addition.changed
