---

# Setup Varnish repository

# Prepare yum repositories
- name: Install repositories
  yum:
    pkg={{item}}
    state=present
    disable_gpg_check=yes
  with_items:
    - "https://repo.varnish-cache.org/redhat/varnish-4.1.el7.rpm"
  when:
    distro == "rhel7"

- name: Install repositories
  yum:
    pkg={{item}}
    state=present
    disable_gpg_check=yes
  with_items:
    - "https://repo.varnish-cache.org/redhat/varnish-4.1.el7.rpm"
  when:
    distro == "centos7"
