
development_packages:
 - nano
 - ruby-devel
 - sqlite-devel
 - gcc-c++

xdebug:
 - section: XDebug
   options:
    - key: xdebug.remote_enable
      val: 1
    - key: xdebug.remote_handler
      val: dbgp
    - key: xdebug.remote_connect_back
      val: 1
    - key: xdebug.remote_port
      val: 9000
    - key: xdebug.remote_autostart
      val: 0

# this can be set to true to add the remote log file.
xdebug_remote_debug_log: false

# mailhog configuration.
mailhog_binary_url: https://github.com/mailhog/MailHog/releases/download/v0.1.7/MailHog_linux_amd64
mailhog_install_dir: /opt/mailhog

# ssmtp configuration.
ssmtp_mailhub: localhost:1025
ssmtp_root: postmaster
ssmtp_authuser: ""
ssmtp_authpass: ""
ssmtp_from_line_override: "YES"
