blackfire_server_key: "aa-bb-REPLACE THIS-cc-dd"
blackfire_server_token: "aa-bb-REPLACE THIS-cc-dd"
blackfire_client_key: "aa-bb-REPLACE THIS-cc-dd"
blackfire_client_token: "aa-bb-REPLACE THIS-cc-dd"
