# These contain the IP addresses from the admin VPN
vpn_ip_list:
  - 127.0.0.1
  - 127.0.0.2

# These servers will do the automatic deployments into the machines
deployment_server_ip_list:
  - 10.254.254.254
  - 10.0.0.1

# Remove older IP addresses which are not needed anymore
removable_legacy_firewall_rules:
  # This is older deploybot address space
  - direction: in
    family: IPv4
    protocol: tcp
    source_address_end: 127.0.0.1
    source_address_start: 127.0.0.255
    destination_port_start: 22
    destination_port_end: 22
    action: accept

# These are the basic rules for load balancers
web_firewall_rules:
  - direction: in
    family: IPv4
    protocol: tcp
    destination_port_start: 80
    destination_port_end: 80
    action: accept

  - direction: in
    family: IPv4
    protocol: tcp
    destination_port_start: 443
    destination_port_end: 443
    action: accept