# These contain the IP addresses from the admin VPN
firewall_ssh_allowed:
  #- comment: Admin machine
  #  ip: 10.0.0.1
  #- comment: Test Machine
  #  ip: 127.0.0.1

# These servers will do the automatic deployments into the machines
project_additional_ssh_firewall_rules:
  #- comment: Admin machine
  #  ip: 10.0.0.1
  #- comment: Test Machine
  #  ip: 127.0.0.1

# Ensure that these older IP addresses are removed
remove_ssh_firewall_rules:
  #- comment: Admin machine
  #  ip: 10.0.0.1
  #- comment: Test Machine
  #  ip: 127.0.0.1

# These are added after ssh rules
project_additional_firewall_rules:
#- direction: in
#  family: IPv4
#  protocol: tcp
#  source_address_start: 127.0.0.1
#  source_address_end: 127.0.0.255
#  destination_port_start: 22
#  destination_port_end: 22
#  action: accept