
varnish:
  port: 8081
  memory: 1G
  probe_resource_url: "_ping.php"
  error_header_cache_control: "no-cache, max-age: 0, must-revalidate"
  error_header_x_site_name: "insert_sitename"
  error_header_x_sitetitle: "insert_site_title"
  error_header_x_ua: "insert_GA_code"
  acl_internal:
    - ip: 127.0.0.1
  acl_purge:
    - ip: 127.0.0.1
  acl_upstream_proxy:
    - ip: 127.0.0.1
  directors:
    # One app
    - name: test_com_director
      host: test.com
      backends:
        - name: test1_web
          address: 127.0.0.1
          port: 8080

# # Multiple apps
#   - name: test_com_director
#     host: test.com
#     backends:
#       - name: test1_web
#         address: 192.168.1.101
#         port: 8080
#   - name: test2_com_director
#     host: test2.com
#     backends:
#       - name: test2_web
#         address: 192.168.1.102
#         port: 8081
#   - name: test3_com_director
#     host: test3.com
#     backends:
#       - name: test3_web
#         address: 192.168.1.102
#         port: 8081
