---

certbot_src: /root
certbot_email: test@example.com
certbot_domains:
  - "{{ ansible_fqdn }}"
certbot_renewal_docroot: /var/www/certbot-auto
certbot_command: "{{ certbot_src }}/certbot/certbot-auto certonly --renew-by-default --standalone --standalone-supported-challenges http-01 --agree-tos --text {% for domain in certbot_domains %}-d {{ domain }} {% endfor %}--email {{ certbot_email }}"
