---

# Create /var/log partition for secondary hard drive
# Secondary hard drive added in the UpCloud UI (recognized as /dev/vdb)

- name: Check if partition named '/var/log' exists
  shell: "mountpoint /var/log"
  register: varlog
  ignore_errors: True
- name: Create partition to secondary drive
  shell: echo -e "n\np\n1\n\n\nw\n" | fdisk "{{ var_log_disk }}"
  when: varlog.rc != 0
- name: Format the partition in the secondary drive
  shell: mkfs.ext4 "{{ var_log_disk }}"1
  when: varlog.rc != 0
- name: Create temp mount point to copy files from current /var/log
  shell: mkdir -p /mnt/varlog && mount "{{ var_log_disk }}"1 /mnt/varlog
  when: varlog.rc != 0
- name: Copy files from old /var/log
  shell: cp -rpf /var/log/* /mnt/varlog/.
  when: varlog.rc != 0
- name: Unmount temp mount and delete current /var/log
  shell: umount /mnt/varlog && rm -rf /mnt/varlog && rm -rf /var/log
  when: varlog.rc != 0
- name: Create /var/log mount point and mount the partition
  shell: mkdir -p /var/log && mount "{{ var_log_disk }}"1 /var/log
  when: varlog.rc != 0
- name: Get UUID of disk
  shell: blkid "{{ var_log_disk }}"1 -o value
  register: var_log_uuid
- name: Add automount for the drive
  lineinfile: dest=/etc/fstab line="UUID={{ var_log_uuid.stdout_lines[0] }} /var/log ext4 defaults 0 0"
  #  when: varlog.rc != 0
