---

# This is the base datadog role to install datadog monitoring

- include:
    "yum.yml"
  when:
    datadog_enabled == True

# Datadog, if enabled
- yum:
    name=datadog-agent
    state=present
  when:
    datadog_enabled == True

- name: Create Datadog configuration
  shell: sudo sh -c "sed 's/api_key:.*/api_key: {{datadog_api_key}}/' /etc/dd-agent/datadog.conf.example > /etc/dd-agent/datadog.conf"
  notify:
    - restart datadog
  when:
    datadog_enabled == True
