---

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: restart sshd
  service: name=sshd state=restarted

- name: restart network
  service: name=network state=restarted

- name: reboot host
  shell: sleep 2 && /sbin/shutdown -r now "Reboot after system update"
  async: 0
  poll: 0
  ignore_errors: true
  failed_when: False
  notify:
    - wait for back online

- name: wait for back online
  local_action: wait_for host={{ ansible_default_ipv4.address }} port={{ ansible_port|default(22) }} delay=5 timeout=320 state=started
