# These variables are used to give hostnames for the new machines
# upcloud_server_hostname_base_domain: client-name.example.com
# upcloud_project_name: Client-Name

# This is a list of allowed ssh-keys for the root user after creating the new servers
# upcloud_server_admin_ssh_keys:
#  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCzZ...
#  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8gOdvY...
#

##
# Example machine configuration
##
#upcloud_server_spec_list:
#      - group: production
#        members:
#          - { name: web1, state: present }
#        settings:
#          plan: 6xCPU-8GB
#          zone: de-fra1
#          # Allows ansible to reboot the machine when making changes to the disks
#          allow_reboot_on_resize: true
#          storage_devices:
#            - title: root
#              os: CentOS 7.0
#              size: 200
#              backup_rule: { interval: daily, time: '0430', retention: 14 }
#            - title: logs
#              size: 10
#              mount:
#                path: /var/log
#                fstype: ext4
#                opts: defaults,noatime
#            - title: database
#              size: 30
#              mount:
#                path: /var/lib/mysql
#                fstype: ext4
#                # Options for mysql performance
#                # These are the same as Mozilla is using for their servers: https://bugzilla.mozilla.org/show_bug.cgi?id=874039
#                opts: defaults,noatime,data=writeback,barrier=0,dioread_nolock
#              backup_rule: { interval: daily, time: '0430', retention: 14 }
#            # Swap is recommended for system stability and when it's a partition it can be excluded from backups
#            # Upcloud minimum partition is 10gb
#            - title: swap
#              size: 10
#              mount:
#                path: none
#                fstype: swap
#                state: present
#                opts: sw
#      - group: stage
#        members:
#          - { name: web1, state: present }
#        settings:
#          plan: 2xCPU-2GB
#          zone: de-fra1
#          # Allows ansible to reboot the machine when making changes to the disks
#          allow_reboot_on_resize: true
#          storage_devices:
#            - title: root
#              size: 50
#              os: CentOS 7.0
#              backup_rule: { interval: daily, time: '0430', retention: 14 }
#            - title: logs
#              size: 10
#              mount:
#                path: /var/log
#                fstype: ext4
#                opts: noatime