---

- include: yum.yml

- yum:
    name={{ item }}
    state=present
  with_items:
    - blackfire-agent
    - blackfire-php

# Add blackfire keys straight to the file (the config --register did not work).
- replace:
    dest=/etc/blackfire/agent
    regexp='server-id=.*$'
    replace='server-id={{ blackfire_server_key }}'
    backup=yes
  notify:
    restart blackfire-agent

- replace:
    dest=/etc/blackfire/agent
    regexp='server-token=.*$'
    replace='server-token={{ blackfire_server_token }}'
    backup=yes
  notify:
    restart blackfire-agent


- template:
    src=blackfire.ini.j2
    dest=/root/.blackfire.ini
    owner=root
    mode=0600
  notify:
    restart blackfire-agent
