---

# Install all php packages
- name: Install php-fpm
  yum: pkg={{ php_package }}-fpm state=present

- name: Ensure php-fpm is running now and on boot
  service: name=php-fpm state=started enabled=yes

- name: Install php packages
  yum: pkg={{ item }} state=present
  with_items:
    - "{{ php_package }}-cli"
    - "{{ php_package }}-common"
    - "{{ php_package }}-devel"
    - "{{ php_package }}-gd"
    - "{{ php_package }}-json"
    - "{{ php_package }}-mbstring"
    - "{{ php_package }}-mcrypt"
    - "{{ php_package }}-mysql"
    - "{{ php_package }}-opcache"
    - "{{ php_package }}-pdo"
    - "{{ php_package }}-pear"
    - "{{ php_package }}-soap"
    - "{{ php_package }}-tidy"
    #- "{{ php_package }}-pecl-imagick"
    #- "{{ php_package }}-pecl-memcache"
    #- "{{ php_package }}-pecl-uploadprogress"
    - "{{ php_package }}-xml"
    - "{{ php_package }}-xmlrpc"

# Install pecl-imagick package
- name: Install pecl-imagick
  yum: pkg={{ php_package }}-pecl-imagick enablerepo=ius-testing state=present